[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.ci]
fuzz = { runs = 100 }
invariant = { runs = 10 }

